version: 0.2

env:
  variables:
    MONGO_URI: mongodb://127.0.0.1:27017/5toalfondo
    BACK_PORT: 5000
    NODE_ENV: development
    TOKEN_SECRET: s3cr3t
phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Installing docker y docker-compose...
      - npm install -g docker docker-compose
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - node app.js
      - echo Start and build docker-compose
      - docker-compose build
  post_build:
    commands:
      - echo levanta docker compose docker-compose up
      - docker-compose up
artifacts:
  files:
    - app.js